debug: true

server:
  port: 12345
  servlet:
    session:
      timeout: 86400
    context-path: /ticket
    jsp:
      init-parameters:
        development: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticket?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
    username: root
    password: 123yhd.

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.liangjian.manager.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
